### PR TITLE
Install config files

### PR DESCRIPTION
**Pull request by chapulina**
Fix https://github.com/ignition-release/ign-gazebo3-release/issues/8

### CODE REVIEW

**Comment by chapulina** [comment]
I believe the paths are correct according to:

```
-- Installing: /var/lib/jenkins/workspace/ign-gazebo3-debbuilder/build/ignition-gazebo-3.7.0/debian/tmp/usr/share/ignition/ignition-gazebo3/server.config
-- Installing: /var/lib/jenkins/workspace/ign-gazebo3-debbuilder/build/ignition-gazebo-3.7.0/debian/tmp/usr/share/ignition/ignition-gazebo3/playback_server.config
```

**Review by mjcarroll — APPROVED** [review]

**Review by scpeters — CHANGES_REQUESTED** [review]
I noticed some `.config` files installed elsewhere, let me investigate real quick

**Comment by chapulina** [comment]
> I noticed some .config files installed elsewhere,

Nice catch, @scpeters , tge GUI configs are installed by:

```
usr/share/ignition/ignition-gazebo[0-99]/gui/*
```

Which is in a different package. I'll make the change

**Comment by chapulina** [comment]
Done

**Review by scpeters — APPROVED** [review]
great! now we can increment the revision and rerun the jenkins builds manually or click on the url's from a `--dry-run` of release.py

**Comment by chapulina** [comment]
I can trigger the new release, thanks for the reminder @scpeters

**Pull request merged**
